import { useMemo } from "react"
import { RoleMixBar, pct } from "../shared/DashboardOverviewKit"

const STAT_STYLES = {
  total_users: {
    label: "Total users",
    ring: "ring-rose-100/80",
    bg: "bg-rose-50/90",
    dot: "bg-rose-500",
    text: "text-rose-950",
  },
  active_users: {
    label: "Active users",
    ring: "ring-emerald-100/80",
    bg: "bg-emerald-50/90",
    dot: "bg-emerald-600",
    text: "text-emerald-950",
  },
  inactive_users: {
    label: "Inactive users",
    ring: "ring-slate-200/80",
    bg: "bg-slate-100/90",
    dot: "bg-slate-500",
    text: "text-slate-900",
  },
}

function formatReportDate(iso) {
  if (!iso) return "—"
  try {
    return new Date(iso).toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    })
  } catch {
    return iso
  }
}

function ReportStatCard({ label, value, style }) {
  return (
    <div className={`rounded-2xl px-4 py-3 ring-1 ${style.bg} ${style.ring}`}>
      <div className="flex items-center gap-2">
        <span className={`h-2 w-2 shrink-0 rounded-full ${style.dot}`} />
        <span className={`text-[11px] font-semibold ${style.text}`}>{label}</span>
      </div>
      <p className={`mt-2 text-2xl font-black tabular-nums ${style.text}`}>{value ?? "—"}</p>
    </div>
  )
}

export default function ReportContentView({ content }) {
  const parsed = useMemo(() => {
    if (!content) return null
    try {
      return typeof content === "string" ? JSON.parse(content) : content
    } catch {
      return null
    }
  }, [content])

  const metrics = useMemo(() => {
    if (!parsed || typeof parsed !== "object") return null
    const total = parsed.total_users ?? 0
    const active = parsed.active_users ?? 0
    const inactive =
      parsed.inactive_users ?? (total > 0 ? Math.max(0, total - active) : 0)

    return {
      total_users: total,
      active_users: active,
      inactive_users: inactive,
      total_recruiters: parsed.total_recruiters ?? 0,
      total_hiring_managers: parsed.total_hiring_managers ?? 0,
      generated_at: parsed.generated_at,
      generated_by: parsed.generated_by,
      company_id: parsed.company_id,
    }
  }, [parsed])

  const roleSegments = useMemo(
    () =>
      metrics
        ? [
            { label: "Recruiters", count: metrics.total_recruiters, color: "#7c3aed" },
            {
              label: "Hiring managers",
              count: metrics.total_hiring_managers,
              color: "#f59e0b",
            },
          ]
        : [],
    [metrics]
  )

  if (!metrics) {
    return (
      <pre className="max-h-64 overflow-auto rounded-xl border border-slate-200/80 bg-slate-50/90 p-4 font-mono text-xs leading-relaxed text-slate-700">
        {content}
      </pre>
    )
  }

  const activeRate = pct(metrics.active_users, metrics.total_users)

  return (
    <div className="space-y-4">
      <div className="grid gap-3 rounded-2xl border border-white/60 bg-white/35 px-4 py-3 sm:grid-cols-2">
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
            Generated
          </p>
          <p className="mt-1 text-sm font-semibold text-slate-800">
            {formatReportDate(metrics.generated_at)}
          </p>
        </div>
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
            Generated by
          </p>
          <p className="mt-1 truncate text-sm font-semibold text-violet-900">
            {metrics.generated_by || "—"}
          </p>
        </div>
        {metrics.company_id ? (
          <div className="sm:col-span-2">
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
              Company ID
            </p>
            <p className="mt-1 break-all font-mono text-xs text-slate-600">
              {metrics.company_id}
            </p>
          </div>
        ) : null}
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        {["total_users", "active_users", "inactive_users"].map((key) => (
          <ReportStatCard
            key={key}
            label={STAT_STYLES[key].label}
            value={metrics[key]}
            style={STAT_STYLES[key]}
          />
        ))}
      </div>

      <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-emerald-200/60 bg-emerald-50/50 px-4 py-2.5">
        <span className="text-xs font-semibold text-emerald-900">Activation rate</span>
        <span className="text-lg font-black tabular-nums text-emerald-800">{activeRate}%</span>
        <span className="text-[11px] font-medium text-emerald-700">
          {metrics.active_users} of {metrics.total_users} users active
        </span>
      </div>

      <RoleMixBar
        title="Recruiter vs hiring manager"
        subtitle="Operational role distribution in this report"
        segments={roleSegments}
      />

      <details className="group rounded-xl border border-slate-200/70 bg-white/40">
        <summary className="cursor-pointer list-none px-4 py-2.5 text-xs font-semibold text-slate-600 marker:content-none [&::-webkit-details-marker]:hidden">
          <span className="inline-flex items-center gap-2">
            <span className="text-slate-400 transition group-open:rotate-90">▸</span>
            View raw JSON
          </span>
        </summary>
        <pre className="max-h-48 overflow-auto border-t border-slate-200/60 px-4 py-3 font-mono text-[11px] leading-relaxed text-slate-600">
          {typeof content === "string" ? content : JSON.stringify(parsed, null, 2)}
        </pre>
      </details>
    </div>
  )
}
